# Generated by Django 6.0.6 on 2026-07-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='response',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
